### ISSUE TITLE
SCOM-WinTaskSchedulerMP 

### ISSUE THREAD

**Issue by AbdelkaderHeni** [BCornelissen/SCOM-WinTaskSchedulerMP#10]
Hi
I installed the MP on SCOM 2019 UR3 (console version 10.19.10505.0) but there is no folder added in the Monitoring panel 
tried many time to uninstall and install again without success, the three MPs are successufully imported but no MP added in the Monitoring tab
Could you help with this issue please 

regards,
A.

**Comment by BCornelissen** [comment]
Hello Abdel, The folder appears under the Microsoft Windows Server folder which is already there. SO its not a separate folder on the main level, but underneath Microsoft Windows Server.

**Comment by AbdelkaderHeni** [comment]
Hello Bob
Indeed, Thanks a lot
