### ISSUE TITLE
question regarding performance of task result/status collection

### ISSUE THREAD

**Issue by leepfrog-ger** [BCornelissen/SCOM-WinTaskSchedulerMP#7]
Hi all,

great to see a maintained Scheduled Task MP around here adding support for SCOM 2019/Windows 2019. Until now I've been using the (quite old, vbs-based) MP by Progel which has worked reliably but is quite on the slow end when collecting task exit codes. Even on fast machines it is taking 30-70 seconds to complete (per machine!). 

I'm wondering whether this is significantly improved with the powershell approach this MP uses, can anyone post prcessing times they are experiencing?

Thanks!

**Comment by BCornelissen** [comment]
The speeds depend on the number of tasks you have and the hardware you are on for that machine and how busy it is. generally we have not seen any issues with performance of the scripts. There is a lot of cook-down in this pack built-in by Raphael in the past.
Also, about 2 years back this pack got changed as well in the approach in the powershell scripts. this was to optimize it as well.
hope it helps.
Feel free to test it. By the way, this pack should also work on Win2022 and SCOM 2022 as far as we can see so far.
