### ISSUE TITLE
PKI Certificate Validation report issue

### ISSUE THREAD

**Issue by apstrother** [BCornelissen/SCOM-WinTaskSchedulerMP#9]
When I attempt to run the report, "Expiring Certificate Report", I get the following: The 'Column List' parameter is missing a value.
The Objects portion of the screen at top is auto populated with:
Object:  All Windows Computers
Include: All contained objects, 
Object Class: All Windows Computers
Management Group: mu mgmt group name
The From Date is auto populated with: Today -7 day(s)
To filed is: Today
![image](https://user-images.githubusercontent.com/73845263/97896395-fdcad280-1d02-11eb-9f47-ea7a64e9cb2a.png)

Thank you for your time and assistance!
Tony

**Comment by BCornelissen** [comment]
Hello Tony, can you move this issue to the PKI pack repo? This is the scheduled tasks repo.
